spring.application.name=JobApplicationManagement
spring.datasource.url=jdbc:postgresql://localhost:5432/jobapplicationsystem
spring.datasource.username=postgres
spring.datasource.password=qusa3187

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true